image: "python:3.6"

before_script:
    - chmod +x code/backend/Testing/prediction_model_test.py
    - cd code/backend/Testing
    - pip install -r requirements.txt

fplpp_job1:
     tags:
       - ci
     script:
       - echo fplpp_job1 with prediction_model_test.py running
       
prediction_model_test:
    stage: test
    script:
      - python3 prediction_model_test.py

